# Generated by Django 5.2 on 2025-04-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_requestlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
