# Generated by Django 5.2 on 2025-04-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_equipmentcategory_repairrequest_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='repairrequest',
            name='priority',
        ),
        migrations.DeleteModel(
            name='EquipmentCategory',
        ),
    ]
